### ISSUE TITLE
Label 2 font and touch pin not defined

### ISSUE THREAD

**Issue by myownexperience** [sigmdel/lazmacropad#5]
I get these errors when trying to compile from platform io, i was able to make it work before but i am very new to all of this I am not sure what to do
[{
	"resource": "/c:/Users/--/Downloads/lazmacropad-main (1)/lazmacropad-main/cydMacroPad/.pio/libdeps/esp32dev/TFT_eSPI/TFT_eSPI.h",
	"owner": "cpp",
	"severity": 4,
	"message": "#warning >>>>------>> TOUCH_CS pin not defined, TFT_eSPI touch functions will not be available! [-Wcpp]",
	"startLineNumber": 973,
	"startColumn": 8,
	"endLineNumber": 973,
	"endColumn": 8
}]
and i also get an error on [{
	"resource": "/c:/Users/---/Downloads/lazmacropad-main (1)/lazmacropad-main/cydMacroPad/src/main.cpp",
	"owner": "cpp",
	"severity": 8,
	"message": "wrong type argument to unary plus",
	"startLineNumber": 228,
	"startColumn": 35,
	"endLineNumber": 228,
	"endColumn": 35
}]

**Comment by myownexperience** [comment]
Figured it out if any one else who is new gets this error Line 228 wrong argument to unary plus in src>main.cpp has a + before `tft.SetFreeFont(Label2_Font)` I just deleted the + and was able to compile and upload!

**Comment by sigmdel** [comment]
Removed the errant "+", so this issue can be closed. Thanks to @myownexperience.
